/* Character art, 16x16, one bit per pixel.
 *
 * Generated by tools/gensprites.py, which holds the sprites as editable ASCII.
 * Change the art there and re-run rather than editing the hex below.
 *
 * Each row is a uint16_t; bit n is column n, counting from the left.
 */
#ifndef FT_SPRITES_H
#define FT_SPRITES_H

#include <stdint.h>

#define FT_SPRITE_W 16
#define FT_SPRITE_H 16

static const uint16_t FT_SPRITE_PLAYER[FT_SPRITE_H] = {
    0x0180,
    0x0180,
    0x3FFC,
    0x3FFC,
    0x300C,
    0x366C,
    0x366C,
    0x300C,
    0x33CC,
    0x300C,
    0x3FFC,
    0x3FFC,
    0x0C30,
    0x0C30,
    0x1E78,
    0x0000,
};

static const uint16_t FT_SPRITE_PACKET[FT_SPRITE_H] = {
    0x0000,
    0x0990,
    0x0DB0,
    0x1FF8,
    0x3FFC,
    0x781E,
    0x766E,
    0x766E,
    0x700E,
    0x77EE,
    0x3FFC,
    0x1FF8,
    0x0DB0,
    0x0990,
    0x0000,
    0x0000,
};

static const uint16_t FT_SPRITE_BEACON[FT_SPRITE_H] = {
    0x0180,
    0x0180,
    0x07E0,
    0x0FF0,
    0x1FF8,
    0xDE7B,
    0xDC3B,
    0xDC3B,
    0xDE7B,
    0x1FF8,
    0x0FF0,
    0x07E0,
    0x0180,
    0x0000,
    0x0000,
    0x0000,
};

static const uint16_t FT_SPRITE_LOCK[FT_SPRITE_H] = {
    0x07E0,
    0x0C30,
    0x0C30,
    0x0C30,
    0x7FFE,
    0x7FFE,
    0x6006,
    0x6C36,
    0x6C36,
    0x6006,
    0x6186,
    0x63C6,
    0x6186,
    0x7FFE,
    0x7FFE,
    0x0000,
};

#endif /* FT_SPRITES_H */
