"""Author overworld maps as ASCII and emit them as C tile data.

Maps are drawn here, not in hex. Production maps will stream from the SD card
in this same byte-per-tile format, so nothing about the renderer changes when
they do.

Grass is '*' rather than a quote character: these maps live inside a Python
triple-quoted string.
"""

LEGEND = {
    ".": 0,  # floor
    "#": 1,  # wall
    "~": 2,  # void
    "*": 3,  # grass
    "=": 4,  # cable
    "D": 5,  # door
    "T": 6,  # terminal
    "L": 7,  # locked port
    "C": 8,  # crate
    "H": 9,  # ladder
}

MAPS = {}

# An AREA is a numbered chain of ROOMS, each about a screen, walked left to
# right — see RESEARCH.md. A room is a small authored set-piece: an encounter,
# maybe one obstacle, and something hidden in a corner. It is not a space to
# explore, so rooms are deliberately close to viewport-sized rather than the
# 2.5-screen open fields the first sketch used.

# [1] Wake. No foe, no obstacle: a terminal to teach saving and one exit.
MAPS["cb1"] = ("Cold Boot", 10, """
################
#..............#
#...T..........#
#..............D
#..............#
#.........C....#
#..............#
################
""")

# [2] First encounter. Wider than a screen so the foe is seen before it is
# reached, which is the whole point of visible encounters.
MAPS["cb2"] = ("Boot Corridor", 18, """
####################
#..................#
D.........*........#
#....C.......*.....#
#..................D
#........*.........#
#..................#
####################
""")

# [3] Vertical section. A terrace splits the room and the ladder is the only
# way down; the item on the upper shelf is passed before it can be taken.
MAPS["cb3"] = ("The Drop", 22, """
##################
#................#
D....*...........#
#................#
#......C.........#
#####H############
#................#
#................#
#.........T......#
#................#
#................D
#....*...........#
#................#
##################
""")

# [4] The gate. A sealed side room behind a locked port, which cannot be opened
# until the iButton several chapters later — the reason to come back.
MAPS["cb4"] = ("Cold Gate", 14, """
##################
#................#
D................#
#.....############
#.....#..........#
#.....L.....C....#
#.....#..........#
#.....############
#......*.........D
##################
""")


def parse(art):
    rows = art.strip("\n").split("\n")
    w = max(len(r) for r in rows)
    out = []
    for r in rows:
        r = r.ljust(w, "#")
        out.append([LEGEND[c] for c in r])
    return w, len(rows), out


with open("src/app/ft_maps.h", "w") as fh:
    fh.write("""/* Built-in overworld maps.
 *
 * Generated by tools/genmaps.py, which holds them as editable ASCII art.
 * Edit the maps there and re-run; do not hand-edit the tables below.
 *
 * Production maps will stream from the SD card in this same byte-per-tile
 * format, so the renderer does not change when they do.
 */
#ifndef FT_MAPS_H
#define FT_MAPS_H

#include "../core/ft_map.h"

""")
    for key, (name, scatter, art) in MAPS.items():
        w, h, rows = parse(art)
        fh.write("/* %s: %ux%u tiles (%ux%u px) */\n" % (name, w, h, w * 8, h * 8))
        fh.write("static const uint8_t FT_MAP_%s_TILES[%u] = {\n" % (key.upper(), w * h))
        for r in rows:
            fh.write("    " + ",".join(str(v) for v in r) + ",\n")
        fh.write("};\n\n")
        fh.write(
            'static const FtMap FT_MAP_%s = {FT_MAP_%s_TILES, %u, %u, "%s", %u};\n\n'
            % (key.upper(), key.upper(), w, h, name, scatter))
        print("%-8s %-16s %2ux%-2u tiles  %.2f x %.2f screens"
              % (key, name, w, h, w / 16, h / 8))

    fh.write("#endif /* FT_MAPS_H */\n")

print("wrote src/app/ft_maps.h")
