"""Author overworld maps as ASCII and emit them as C tile data.

Maps are drawn here, not in hex. Production maps will stream from the SD card
in this same byte-per-tile format, so nothing about the renderer changes when
they do.

Grass is '*' rather than a quote character: these maps live inside a Python
triple-quoted string.
"""

LEGEND = {
    ".": 0,  # floor
    "#": 1,  # wall
    "~": 2,  # void
    "*": 3,  # grass
    "=": 4,  # cable
    "D": 5,  # door
    "T": 6,  # terminal
    "L": 7,  # locked port
    "C": 8,  # crate
}

MAPS = {}

# Cold Boot: where the game opens. A terminal to teach saving, a locked port
# that cannot be opened yet so the iButton has somewhere to matter later, and
# two ways out of the first room so it never reads as a corridor.
MAPS["cold_boot"] = ("Cold Boot", 12, """
################################
#....T....#....................#
#.........#.....====.....****..#
#....C....#.....====.....****..#
#.........D.....====...........#
#.........#....................#
#.........#........C......C....#
###D#######....................#
#..............................#
#...****...........#####L#######
#...****...........#...........#
#..........C.......#...C...T...#
#..................#...........#
#......====........#...........#
#......====........#############
################################
""")

# The Scrapline: chapter one. Open ground broken by a void you must route
# around, and the chapter's module sits behind a locked port on the far side,
# so the place is walked twice — once to find it, once to open it.
MAPS["scrapline"] = ("The Scrapline", 26, """
########################################
#......****......########..............#
#......****......#......#....====......#
#................#..C...#....====......#
#....C...........D......#..............#
#................#......#......C.......#
#........~~~~~~~~#......D..............#
#........~~~~~~~~#......#....######L####
#........~~~~~~~~#......#....#.........#
#........~~~~~~~~########....#...T.....#
#........~~~~~~~~...........D..........#
#........~~~~~~~~#....C......#.........#
#................#...........#.........#
#....T...........#....****...#####D#####
#................#....****...#.........#
#......C.........#...........#...C.....#
#................D...........#.........#
#................#...........#.........#
#......====......#.....C.....#.........#
########################################
""")


def parse(art):
    rows = art.strip("\n").split("\n")
    w = max(len(r) for r in rows)
    out = []
    for r in rows:
        r = r.ljust(w, "#")
        out.append([LEGEND[c] for c in r])
    return w, len(rows), out


with open("src/app/ft_maps.h", "w") as fh:
    fh.write("""/* Built-in overworld maps.
 *
 * Generated by tools/genmaps.py, which holds them as editable ASCII art.
 * Edit the maps there and re-run; do not hand-edit the tables below.
 *
 * Production maps will stream from the SD card in this same byte-per-tile
 * format, so the renderer does not change when they do.
 */
#ifndef FT_MAPS_H
#define FT_MAPS_H

#include "../core/ft_map.h"

""")
    for key, (name, scatter, art) in MAPS.items():
        w, h, rows = parse(art)
        fh.write("/* %s: %ux%u tiles (%ux%u px) */\n" % (name, w, h, w * 8, h * 8))
        fh.write("static const uint8_t FT_MAP_%s_TILES[%u] = {\n" % (key.upper(), w * h))
        for r in rows:
            fh.write("    " + ",".join(str(v) for v in r) + ",\n")
        fh.write("};\n\n")
        fh.write(
            'static const FtMap FT_MAP_%s = {FT_MAP_%s_TILES, %u, %u, "%s", %u};\n\n'
            % (key.upper(), key.upper(), w, h, name, scatter))
        print("%-12s %2ux%-2u tiles  (%u px wide, %.1f screens)" % (key, w, h, w * 8, w / 16))

    fh.write("#endif /* FT_MAPS_H */\n")

print("wrote src/app/ft_maps.h")
