"""Author the 1-bit character art as ASCII, preview it, and emit a C header.

Sprites live here rather than in hand-written hex so they stay editable: change
the ASCII, re-run, look at the PNG.
"""
import sys
from PIL import Image

SPRITES = {}

# Art rules that survive 16x16 at one bit: a solid 2px silhouette, a white
# interior, and dark features at least 2x2 inside it. Mixing thin outline with
# fill turns to mush at this size.

# The player: a handheld device with a face on its screen and stubby legs.
SPRITES["player"] = """
.......##.......
.......##.......
..############..
..############..
..##........##..
..##.##..##.##..
..##.##..##.##..
..##........##..
..##..####..##..
..##........##..
..############..
..############..
....##....##....
....##....##....
...####..####...
................
"""

# Stray Packet: a spiked ball. Deliberately round and legless so it cannot be
# mistaken for the boxy, footed player.
SPRITES["packet"] = """
................
....#..##..#....
....##.##.##....
...##########...
..############..
.####......####.
.###.##..##.###.
.###.##..##.###.
.###........###.
.###.######.###.
..############..
...##########...
....##.##.##....
....#..##..#....
................
................
"""

# Drift Beacon: an airborne eye. Round body, solid pupil, swept wings and a
# pulse antenna, so AIRBORNE reads instantly.
SPRITES["beacon"] = """
.......##.......
.......##.......
.....######.....
....########....
...##########...
##.####..####.##
##.###....###.##
##.###....###.##
##.####..####.##
...##########...
....########....
.....######.....
.......##.......
................
................
................
"""

# Sealed Lock: a padlock with a scowl. Tall shackle above a heavy body.
SPRITES["lock"] = """
.....######.....
....##....##....
....##....##....
....##....##....
.##############.
.##############.
.##..........##.
.##.##....##.##.
.##.##....##.##.
.##..........##.
.##....##....##.
.##...####...##.
.##....##....##.
.##############.
.##############.
................
"""


def parse(art):
    rows = [r for r in art.strip("\n").split("\n") if r.strip()]
    assert len(rows) == 16, f"need 16 rows, got {len(rows)}"
    out = []
    for r in rows:
        r = (r + "." * 16)[:16]
        bits = 0
        for x, ch in enumerate(r):
            if ch == "#":
                bits |= 1 << x  # bit x = column x, LSB leftmost
        out.append(bits)
    return out


def main():
    data = {k: parse(v) for k, v in SPRITES.items()}

    # Contact sheet so the art can actually be looked at.
    scale, pad = 6, 8
    sheet = Image.new("L", (len(data) * (16 * scale + pad) + pad, 16 * scale + 2 * pad), 200)
    for i, (name, rows) in enumerate(data.items()):
        img = Image.new("L", (16, 16), 255)
        px = img.load()
        for y, bits in enumerate(rows):
            for x in range(16):
                if bits & (1 << x):
                    px[x, y] = 0
        img = img.resize((16 * scale, 16 * scale), Image.NEAREST)
        sheet.paste(img, (pad + i * (16 * scale + pad), pad))
    sheet.save("tools/sprites.png")

    with open("src/app/ft_sprites.h", "w") as fh:
        fh.write("""/* Character art, 16x16, one bit per pixel.
 *
 * Generated by tools/gensprites.py, which holds the sprites as editable ASCII.
 * Change the art there and re-run rather than editing the hex below.
 *
 * Each row is a uint16_t; bit n is column n, counting from the left.
 */
#ifndef FT_SPRITES_H
#define FT_SPRITES_H

#include <stdint.h>

#define FT_SPRITE_W 16
#define FT_SPRITE_H 16

""")
        for name, rows in data.items():
            fh.write(f"static const uint16_t FT_SPRITE_{name.upper()}[FT_SPRITE_H] = {{\n")
            for r in rows:
                fh.write("    0x%04X,\n" % r)
            fh.write("};\n\n")
        fh.write("#endif /* FT_SPRITES_H */\n")

    print(f"wrote src/app/ft_sprites.h and tools/sprites.png ({len(data)} sprites)")


main()
