"""Author the 8x8 overworld tiles as ASCII, preview them, and emit a C header.

Same approach as gensprites.py: the art is editable text, not hand-written hex.
"""
from PIL import Image, ImageDraw

TILES = {}

# Walkable ground. Sparse stipple so large areas read as floor without
# vibrating — a dense pattern is unbearable at this size.
TILES["floor"] = """
........
..#.....
........
.....#..
........
..#.....
........
.....#..
"""

# Wall FACE: the south-facing side, used where floor lies below. Brick courses
# with a solid base row so the wall looks like it stands on the ground.
TILES["wall"] = """
########
#..#..##
########
#..##..#
########
##..#..#
########
########
"""

# Wall TOP: the cap, used where the wall continues below. Near-solid so it
# reads as mass rather than as another face — the contrast between this and
# the brick face is what gives a wall run its height.
TILES["wall_top"] = """
########
########
###.####
########
########
####.###
########
########
"""

# Shadow cast onto whatever tile sits under a wall. 50% dither, because on a
# one-bit panel a solid band would just look like more wall.
TILES["shadow"] = """
#.#.#.#.
.#.#.#.#
........
........
........
........
........
........
"""

# Void / drop. Solid black: nothing there, and unmistakably not floor.
TILES["void"] = """
########
########
########
########
########
########
########
########
"""

# Tall grass. Walkable, hides things, rustles.
TILES["grass"] = """
........
..#..#..
.#.##.#.
.#.##.#.
#.####.#
........
...##...
..####..
"""

# Cable conduit: decorative floor that reads as "this place is machinery".
TILES["cable"] = """
........
########
.#....#.
........
........
.#....#.
########
........
"""

# Door seen face-on. Correct only in a HORIZONTAL wall, where you walk up or
# down through it. Heavy frame, clear opening, handle on the right.
TILES["door"] = """
########
##....##
#......#
#......#
#......#
#......#
#......#
#......#
"""

# The same door in a VERTICAL wall, where you pass left-to-right. Drawn as a
# gap with the wall continuing above and below — a face-on door here reads as
# if it were lying on its back.
TILES["door_side"] = """
########
#......#
........
........
........
........
#......#
########
"""

# Locked port in a vertical wall: the same gap, barred.
TILES["lock_side"] = """
########
#......#
.##..##.
.##..##.
.##..##.
.##..##.
#......#
########
"""

# A single weed, scattered procedurally over floor (see ft_map_scatter).
# Kept inset from the tile edges so neighbouring tufts never merge into a
# hedge, and kept light so it does not fight the floor stipple.
TILES["tuft"] = """
........
........
...#....
..###...
...#....
........
........
........
"""

# Conduit running vertically, for cable runs that go up the screen.
TILES["cable_v"] = """
.#....#.
.#....#.
.#....#.
.#....#.
.#....#.
.#....#.
.#....#.
.#....#.
"""

# Terminal: save point and full restore. Deliberately a heavy, mostly-solid
# monitor on a narrow post — an outlined box here is indistinguishable from a
# crate at 8x8.
TILES["term"] = """
.######.
.######.
.#....#.
.#.##.#.
.######.
...##...
..####..
........
"""

# Locked port. Opened by the iButton module, once it is recovered.
TILES["lock"] = """
..####..
.##..##.
.#....#.
########
##....##
##.##.##
##....##
########
"""

# Crate: pushable, or just cover. X-braced so its silhouette is diagonal
# rather than another concentric square.
TILES["crate"] = """
########
##....##
#.#..#.#
#..##..#
#..##..#
#.#..#.#
##....##
########
"""


def parse(art):
    rows = [r for r in art.strip("\n").split("\n") if r.strip() or True]
    rows = [r for r in art.strip("\n").split("\n")]
    assert len(rows) == 8, f"need 8 rows, got {len(rows)}"
    out = []
    for r in rows:
        r = (r + "." * 8)[:8]
        bits = 0
        for x, ch in enumerate(r):
            if ch == "#":
                bits |= 1 << x
        out.append(bits)
    return out


data = {k: parse(v) for k, v in TILES.items()}

scale, pad = 8, 6
sheet = Image.new("L", (len(data) * (8 * scale + pad) + pad, 8 * scale + 2 * pad + 10), 200)
draw = ImageDraw.Draw(sheet)
for i, (name, rows) in enumerate(data.items()):
    img = Image.new("L", (8, 8), 255)
    px = img.load()
    for y, bits in enumerate(rows):
        for x in range(8):
            if bits & (1 << x):
                px[x, y] = 0
    ox = pad + i * (8 * scale + pad)
    draw.text((ox, 0), name, fill=0)
    sheet.paste(img.resize((8 * scale, 8 * scale), Image.NEAREST), (ox, 10 + pad // 2))
sheet.save("tools/tiles.png")

with open("src/app/ft_tiles.h", "w") as fh:
    fh.write("""/* Overworld tile art, 8x8, one bit per pixel.
 *
 * Generated by tools/gentiles.py, which holds the tiles as editable ASCII.
 * Change the art there and re-run rather than editing the hex below.
 *
 * Each row is a uint8_t; bit n is column n, counting from the left.
 */
#ifndef FT_TILES_H
#define FT_TILES_H

#include <stdint.h>

#include "../core/ft_map.h"

static const uint8_t FT_TILE_ART[FT_TILE_ART_COUNT][FT_TILE_PX] = {
""")
    # Must match FtTile, then the orientation variants (FT_TILE_ART_*).
    order = ["floor", "wall", "void", "grass", "cable", "door", "term", "lock", "crate",
             "door_side", "lock_side", "cable_v", "wall_top", "shadow", "tuft"]
    for name in order:
        fh.write("    /* %-6s */ {%s},\n" % (name, ", ".join("0x%02X" % b for b in data[name])))
    fh.write("};\n\n#endif /* FT_TILES_H */\n")

print("wrote src/app/ft_tiles.h and tools/tiles.png (%d tiles)" % len(data))
